"""track image processing status

Revision ID: 7e196924cd60
Revises: 6e44ca0db6b9
Create Date: 2026-09-12 12:41:28.053003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e196924cd60'
down_revision: Union[str, Sequence[str], None] = '6e44ca0db6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('images', sa.Column('error', sa.Text(), nullable=True))
    op.alter_column('images', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('images', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('images', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('images', 'caption',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('images', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_images_status'), 'images', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_status'), table_name='images')
    op.alter_column('images', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('images', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('images', 'caption',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('images', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('images', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('images', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('images', 'error')
    op.drop_column('images', 'status')
    # ### end Alembic commands ###
