"""add AI call tracking

Revision ID: ac8ee933aa7f
Revises: f42d78da1f2b
Create Date: 2026-09-12 13:39:43.651564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8ee933aa7f'
down_revision: Union[str, Sequence[str], None] = 'f42d78da1f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_calls_operation'), 'ai_calls', ['operation'], unique=False)
    op.create_index(op.f('ix_ai_calls_success'), 'ai_calls', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_calls_success'), table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_operation'), table_name='ai_calls')
    op.drop_table('ai_calls')
    # ### end Alembic commands ###
